arquivo:
  caminho: C:\lds-arquivos\
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/boturussu
#    password: root
#    username: root
    url: jdbc:mysql://lds-boturussu.chkg8ypjguo6.sa-east-1.rds.amazonaws.com/boturussu
    password: boturussu
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
